name: Build & Deploy to K8s
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3.12.0
      - name: login to docker registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Frontend Image
        uses: docker/build-push-action@v6.18.0
        with:
          path: ./client
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/tourapp-frontent:latest
      - name: Build & push backend image
        uses: docker/build-push-action@v6.18.0
        with:
          path: ./server
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_TOKEN }}/tourapp-backend:latest
          push: true
        

          
      
  deploy:
